# Generated by Django 3.0.8 on 2021-06-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductLowestPrice', models.CharField(max_length=10)),
                ('LastUpdated', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Productid', models.CharField(max_length=100)),
                ('VariationText', models.CharField(max_length=100)),
                ('Stock', models.CharField(max_length=100)),
                ('LastUpdated', models.DateField(blank=True)),
            ],
        ),
    ]
