# Generated by Django 3.0.8 on 2021-06-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlist',
            old_name='id',
            new_name='SlNo',
        ),
    ]
