# Generated by Django 3.0.8 on 2021-06-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210630_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='Stock',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productlist',
            name='VariationText',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
