# Generated by Django 3.0.8 on 2021-06-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210701_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='Stock',
        ),
        migrations.RemoveField(
            model_name='productlist',
            name='VariationText',
        ),
    ]
